#ifndef CONSTANTES_H
#define CONSTANTES_H

/* Red */
#define PUERTO_SERVIDOR 5000
#define IP_SERVIDOR "127.0.0.1"

/* Pantalla */
#define ANCHO_PANTALLA 800
#define ALTO_PANTALLA 600

/* UI y estructuras del juego */
#define BUNKER_CANTIDAD 4
#define BUNKER_ANCHO 60
#define BUNKER_ALTO 35
#define BUNKER_LIFE_INICIAL 100
#define BUNKER_LIFE_ALTA 75
#define BUNKER_LIFE_MEDIA 50
#define BUNKER_LIFE_BAJA 25
#define BUNKER_Y_OFFSET 150
#define BUNKER_POS_0 120
#define BUNKER_POS_1 275
#define BUNKER_POS_2 430
#define BUNKER_POS_3 585
#define BUNKER_TEXTO_INICIAL "100%"

#define ALIEN_FILAS 4
#define ALIEN_COLUMNAS 10
#define ALIEN_ANCHO 30
#define ALIEN_ALTO 20
#define ALIEN_X_INICIAL 100
#define ALIEN_Y_INICIAL 60
#define ALIEN_X_SEPARACION 48
#define ALIEN_Y_SEPARACION 34
#define ALIEN_DESCENSO 16
#define ALIEN_MARGEN_BORDE 20

#define OVNI_ANCHO 48
#define OVNI_ALTO 20
#define OVNI_Y_INICIAL 25

#define PROYECTIL_ANCHO 4
#define PROYECTIL_ALTO 10
#define PROYECTIL_ALIEN_X_OFFSET 12
#define PROYECTIL_ALIEN_Y_OFFSET 20
#define PROYECTIL_JUGADOR_Y_OFFSET 10

#define BUFFER_BUNKERS 32
#define BUFFER_MENSAJE 64
#define BUFFER_RECV 1024
#define BUFFER_LINEA 1024
#define BUFFER_ENVIO 256
#define BUFFER_ROL 16

/* Logica del juego */
#define VIDAS_INICIALES 3
#define PTS_CALAMAR 10
#define PTS_CANGREJO 20
#define PTS_PULPO 40
#define VELOCIDAD_CANON 5
#define ANCHO_CANON 40
#define ALTO_CANON 20
#define VELOCIDAD_PROYECTIL_JUGADOR 8
#define VELOCIDAD_DISPARO_ALIEN 6
#define INTERVALO_DISPARO_ALIEN_MS 900
#define RETARDO_DISPARO_SALIDA_MS 1000
#define TASA_DISPARO_BUNKER_JUGADOR 20
#define TASA_DISPARO_BUNKER_ALIEN 10

/* Controlador fisico (Pico via UART USB / CDC serial) */
#define UART_BAUD_RATE 115200
#define PUERTO_SERIAL "COM4"

/* Protocolo de comandos (1 byte ASCII, igual que Controlador/constants.h) */
#define CMD_LEFT 'L'
#define CMD_RIGHT 'R'
#define CMD_FIRE 'F'

#endif /* CONSTANTES_H */